import type { Metadata } from "next";
import "./globals.scss";
import localFont from "next/font/local";

const agrandir = localFont({
  src: "../../public/fonts/Agrandir-Regular.otf",
  variable: "--font-body",
});

const tanHeadline = localFont({
  src: "../../public/fonts/Tan-Headline.otf",
  variable: "--font-heading",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${agrandir.variable} ${tanHeadline.variable}`}>
        {children}
      </body>
    </html>
  );
}
