import type { Metadata } from "next";
import "./globals.scss";
import { Outfit } from "next/font/google";
import localFont from "next/font/local";
import { DesktopNav } from "../components/desktop_nav";
import { navLinks } from "../utils/data";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-body",
});

const tanHeadline = localFont({
  src: "../../public/fonts/Tan-Headline.otf",
  variable: "--font-heading",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} ${tanHeadline.variable}`}>
        <DesktopNav links={navLinks} />
        {children}
      </body>
    </html>
  );
}
